version: '3'

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: app

services:
  db:
    image: mysql:8.0
    environment: *common-variables
    ports:
      - "3306:3306"    
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    environment:
      <<: *common-variables
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid &&  bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
